# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
# title: "App Explained Blog"
description: > # this means to ignore newlines until "email:"
  Kotlin and Android development explained.

email: hello@appexplained.com

# App Explained logo
logo: "/assets/images/logo.png"
# float_logo: true # true, false (default)

# Cover image
cover: "/assets/images/cover-image.png"

# Site Name
name: "App Explained"

# Authors
nathan_author_image: "https://avatars1.githubusercontent.com/u/3166572?s=460&u=d387e31cbdaab560321a67a4867528033bbccc3b&v=4"
kim_author_image: "https://avatars3.githubusercontent.com/u/19276188?s=460&u=506c19cb0a66673c474aa72c7e138029df01643b&v=4"

paginate: 5
url: "https://blog.appexplained.com" # the base hostname & protocol for your site
baseurl: ""

twitter_handle: "@appexplained"
# disqus: disqus-shortname
# google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: medium
    url: https://medium.com/appexplained
    desc: Follow me on Medium

  - icon: twitter
    url: https://twitter.com/appexplained
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
